language: android
sudo: false
addons:
  apt:
    packages:
     - p7zip-full
env:
# Build for all suppported architectures in parallel
  - PLATFORM='Mips' BUILD_TYPE='Debug'
  - PLATFORM='Armeabi-v7a'BUILD_TYPE='Debug'
  - PLATFORM='X86' BUILD_TYPE='Debug'
  - PLATFORM='X86_64' BUILD_TYPE='Debug'
  - PLATFORM='Arm64-v8a' BUILD_TYPE='Debug'
# TODO: Check if there's a way to have "orthogonal" environment variables
  - PLATFORM='Mips' BUILD_TYPE='Release'
  - PLATFORM='Armeabi-v7a'BUILD_TYPE='Release'
  - PLATFORM='X86' BUILD_TYPE='Release'
  - PLATFORM='X86_64' BUILD_TYPE='Release'
  - PLATFORM='Arm64-v8a' BUILD_TYPE='Release'

before_install:
  - wget --timeout=120 http://dl.google.com/android/repository/android-ndk-r11b-linux-x86_64.zip -O ndk.zip
  - sha1sum ndk.zip | grep cf0658956945c81d3d3fad5f9a24fa062d4c9d41
  - 7z x ndk.zip > /dev/null
  - export ANDROID_NDK=$(pwd)/android-ndk-r11b
  - printf "ndk.dir=$ANDROID_NDK" > local.properties
  - chmod +x gradlew
# Maybe gradlew is not executable?
install:
  - git submodule update --init --recursive
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
# Workaround for missing dependencies?
before_script:
  - ./gradlew clean --continue
script:
  - ./gradlew assemble${PLATFORM}${BUILD_TYPE} --max-workers=2
android:
  components:
# Android tools are required, see https://github.com/travis-ci/travis-ci/issues/5036
   - tools
   - android-22
   - build-tools-22.0.1
   - extra-android-m2repository
   - extra-support
   - extra
