language: android
sudo: false
addons:
  apt:
    packages:
     - p7zip-full
env:
# Build for all suppported architectures in parallel
  - BUILD_ARCH_LIST='mips'
  - BUILD_ARCH_LIST='armeabi-v7a'
  - BUILD_ARCH_LIST='x86'
  - BUILD_ARCH_LIST='x86_64'
  - BUILD_ARCH_LIST='arm64-v8a'
  - BUILD_ARCH_LIST='mips64'
before_install:
  - wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O ndk.bin
  - md5sum ndk.bin | grep 19af543b068bdb7f27787c2bc69aba7f
  - 7z x ndk.bin > /dev/null
  - export ANDROID_NDK=$(pwd)/android-ndk-r10e
  - printf "ndk.dir=$ANDROID_NDK" > local.properties
  - chmod +x gradlew
# Maybe gradlew is not executable?
install:
  - git submodule update --init --recursive
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
# Workaround for missing dependencies?
before_script:
  - ./gradlew clean --continue
script:
  - ./gradlew assembleDebug
android:
  components:
# Android tools are required, see https://github.com/travis-ci/travis-ci/issues/5036
   - tools
   - android-22
   - build-tools-22.0.1
   - extra-android-m2repository
   - extra-support
   - extra
